### ISSUE TITLE
Edit Sticker Text on Double Tab

### ISSUE THREAD

**Issue by supriya456** [wuapnjie/StickerView#11]
How can I edit sticker text on Double Tab of Sticker view it will help to edit that sticker text can you please help me how should I integrate it in android

**Comment by wuapnjie** [comment]
Currently，you only can single tap to change the text.

**Comment by supriya456** [comment]
Still the text is not changing showing same text

**Comment by wuapnjie** [comment]
Maybe you need to call explicitly stickerView.invalidate()

2016-12-15 12:50 GMT+08:00 supriya456 <notifications@github.com>:

**Comment by supriya456** [comment]
Yes solved issue thanks for help

**Comment by supriya456** [comment]
& one more thing I have to add Edit Sticker Text on Double Tab so what I have to do can you please help me for this one?

**Comment by wuapnjie** [comment]
Ok. I will add double tap callback soon

**Comment by supriya456** [comment]
Great!
Please let me know after adding it......

**Comment by wuapnjie** [comment]
I add a double tap callback.But you double tap also will trigger two click callback, so you need to choose which click you really need. You can check demo to see log in logcat with double tap and click and other events

**Comment by supriya456** [comment]
Yes Sure thanks!

**Comment by ejaz1626** [comment]
I have added more than one text. i want to change color of the text, but problem is that color is changed of the last text. how can i get active sticker to change the color of active sticker?
One more thing i want to add one more sticker image which is used to flip the text vertically.how is this possible?

**Comment by wuapnjie** [comment]
You can hold all TextStickers’ reference.Then you can change all text colors. And I don’t understand the another thing.

**Comment by ejaz1626** [comment]
Dear,
         No, I just want to click on one sticker and change that color using color picker dialog.
Second thing is that i want a button sticker on the fourth corner of sticker which is used to flip the text vertically.
I attached an image, please check this image. 

    On Monday, February 6, 2017 5:30 PM, FlyingSnowBean <notifications@github.com> wrote:
 

 You can hold all TextStickers’ reference.Then you can change all text colors. And I don’t understand the another thing.

**Comment by ejaz1626** [comment]
No, I just want to click on one sticker and change that color using color picker dialog.
Second thing is that i want a button sticker on the fourth corner of sticker which is used to flip the text vertically.
I attached an image, please check this image.
![df](https://cloud.githubusercontent.com/assets/11348759/22649695/f1b1ddde-ec9d-11e6-8793-eb9802183bc8.PNG)

**Comment by wuapnjie** [comment]
You can listening the click event on StickerView.
You can easily check the source code to add flip vertically function. Currently this library does not contains this function.

**Comment by ejaz1626** [comment]
I added the button on StickerView and create  a method for vertical flip.here is code
if (currentMode == ActionMode.FLIP_VERTICAL && handlingSticker != null) {
                    handlingSticker.getMatrix()
                            .preScale(1, -1, handlingSticker.getCenterPoint().x,
                                    handlingSticker.getCenterPoint().y);

                    handlingSticker.setFlipped(!handlingSticker.isFlipped());
                    if (onStickerOperationListener != null) {
                        onStickerOperationListener.onStickerFlippedVertical(handlingSticker);
                    }
                    invalidate();
                }
//But the problem is that when i click the button the whole sticker orientation is changed.

**Comment by wuapnjie** [comment]
You can check this latest update. [commit](https://github.com/wuapnjie/StickerView/commit/04e4c63fbec8db82165c32eefdfce27df989237b)
In this update, you can easily config your sticker icon and its event and its position.You can check it in latest demo or readme.
And this library contains four origin event: DeleteIconEvent    FlipHorizontallyEvent    FlipVerticallyEvent  and ZoomIconEvent.  You can see them in source code.

**Comment by ejaz1626** [comment]
thank you sir its really helpful.
But Please, change the gradle version to (gradle-2.14.1-all.zip).
I am stucked in the beta version of android studio. I am not able to change the gradle version (gradle-2.14.1-all.zip) to (gradle-3.3-all.zip) for two days. I am not able to change the build tool from (classpath 'com.android.tools.build:gradle:2.2.3') to (classpath 'com.android.tools.build:gradle:2.3.0-beta3').
please convert it into lower version that is (gradle-2.14.1-all.zip)  and build tools to (classpath 'com.android.tools.build:gradle:2.2.3').

**Comment by wuapnjie** [comment]
You can edit this config by yourself.

**Comment by ejaz1626** [comment]
How can i get current current touching TextSticker to change the text color?
I have added more than one text using dialog with input field edittext. i want to change different color for different text.
//here is my peace of code for adding text using custom dialog on button click:
LayoutInflater layoutInflaterAndroid = LayoutInflater.from(StickerViewActivity.this);
                View mView = layoutInflaterAndroid.inflate(R.layout.cust_dialog, null);
                AlertDialog.Builder alertDialogBuilderUserInput = new AlertDialog.Builder(StickerViewActivity.this);
                alertDialogBuilderUserInput.setView(mView);

                final EditText userInputDialogEditText = (EditText) mView.findViewById(R.id.userInputDialog);
                alertDialogBuilderUserInput
                        .setCancelable(false)
                        .setPositiveButton("Add Text", new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialogBox, int id) {
                                sticker = new TextSticker(getApplicationContext());
                                sticker.setDrawable(
                                        ContextCompat.getDrawable(getApplicationContext(),R.drawable.transparent_background));
                                string = userInputDialogEditText.getText().toString();
                                sticker.setText(string + "");
                                sticker.setMaxTextSize(16);
                                sticker.resizeText();
                                stickerView.addSticker(sticker);
                                stickerView.invalidate();
                            }
                        }).setNegativeButton("Cancel",
                        new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialogBox, int id) {
                                dialogBox.cancel();
                            }
                        });

                AlertDialog alertDialogAndroid = alertDialogBuilderUserInput.create();
                alertDialogAndroid.show();

//And this is how i am changing color of text
private void ColorPickerDialog() {
        int initialColor = Color.RED;
        ColorPickerDialog colorPickerDialog = new ColorPickerDialog(
                StickerViewActivity.this, initialColor,
                new ColorPickerDialog.OnColorSelectedListener() {
                    @Override
                    public void onColorSelected(int color) {
                        stickerView.getCurrentSticker();
                            sticker.setTextColor(color);
                            stickerView.invalidate();
                    }
                });
        colorPickerDialog.show();
    }
PROBLEM: problem is that whet i add text and change that color it is changed.And i add another text and change that color, it is changed. But when i touch or click the first text and want to change the color,
color of first text does not change. Color of second text is changed, first text color is not changed On which i click or touch.

**Comment by wuapnjie** [comment]
You can set a listener to listen all events.Just like click,drag,zoom and
more.

**Comment by ejaz1626** [comment]
I do not understand. how can i set listener?

**Comment by wuapnjie** [comment]
stickerView.setOnStickerOperationListener

2017年2月9日 下午8:57，"ejaz1626" <notifications@github.com>写道：

I do not understand. how can i set listener?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/wuapnjie/StickerView/issues/11#issuecomment-278633078>,
or mute the thread

**Comment by ejaz1626** [comment]
I have set listener.
The color of all the text is changed when i click.
I want to set different color for different text.

**Comment by ejaz1626** [comment]
please help me 
i have a problem to set different text color for different text.
please!

**Comment by wuapnjie** [comment]
Sorry. In my test.  I can change the text  color separately.

**Comment by ejaz1626** [comment]
I also can change the text color separately.
But at first time i can change the text color and i add another text and change that color.
When i click the first text, the text color is not changed, on the same time the color of second text is changed which i added.

**Comment by wuapnjie** [comment]
You can check the latest demo now.

**Comment by ejaz1626** [comment]
Thank you so much for your effort.
i can apply this before. it is not my solution.
thanks again i shall solve my problem by myself.
Thanks for giving your valuable time.
And sorry for too much disturbance!

**Comment by kyky04** [comment]
The String of Current Textsticker cannot be change :
@Override public void onStickerClicked(Sticker sticker) {
        //stickerView.removeAllSticker();
        if (sticker instanceof TextSticker) {
          ((TextSticker) sticker).setTextColor(Color.RED);
          ((TextSticker) sticker).setText("Test");
          stickerView.replace(sticker);
          stickerView.invalidate();
        }
        Log.d(TAG, "onStickerClicked");
      }
text of current Textsticker still not Changed, but color and the other changed.
can you help me please?

Sorry for my english language

**Comment by awind** [comment]
@kyky04 you can try call `sticker.resizeText()` after change the text of stickerview.

**Comment by nithinpmolethu** [comment]
Is there any code to add shadow to text.
If any way is possible pls let me know

**Comment by chnouman** [comment]
@kyky04  you can change the text via replacing sticker with new one.

**Comment by chnouman** [comment]
Hy can any body help me in sorting out that i'm trying to add new text sticker but its text size on zooming get blurred i need this in good quality.
@wuapnjie @supriya456 @ejaz1626 @kyky04 @awind

**Comment by kyky04** [comment]
@chnouman Try changing the background size of the text
StickerView/tree/master/sticker/src/main/res/drawable/sticker_transparent_background.xml

<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="@android:color/transparent" />
    <size android:width="200dp" android:height="50dp" />
</shape>

i think bigger size is better to get good result

**Comment by chnouman** [comment]
its not working @kyky04 dear.

**Comment by chnouman** [comment]
@kyky04 i'm having difficulty in getting text of textSticker i want to change the font color of textSticker when i do this it replaces text with default text of textSticker. Kindly help me please.

**Comment by chnouman** [comment]
@kyky04  please i need your help i want text shadow.

**Comment by kyky04** [comment]
@chnouman check your email

**Comment by Mayurdudhat** [comment]
how to change text of textsticker?

**Comment by chnouman** [comment]
TextSticker dump = (TextSticker) stickerViewx.getCurrentSticker();
                                    recentText= input.toString();
                                    final TextSticker sticker = new TextSticker(EditingActivity.this);
                                    sticker.setText(input+"");
                                    sticker.setMaxTextSize(500);
                                    sticker.setTextColor(dump.getTextColor());
                                    sticker.setTypeface(dump.getTypeface());
                                    sticker.setTextAlign(Layout.Alignment.ALIGN_CENTER);
                                    sticker.resizeText();
                                    stickerView.replace(sticker);

**Comment by Mayurdudhat** [comment]
TextSticker dump = (TextSticker) stickerViewx.getCurrentSticker();
recentText= input.toString();
final TextSticker sticker = new TextSticker(EditingActivity.this);
sticker.setText(input+"");
sticker.setMaxTextSize(500);
sticker.setTextColor(dump.getTextColor());
sticker.setTypeface(dump.getTypeface());
sticker.setTextAlign(Layout.Alignment.ALIGN_CENTER);
sticker.resizeText();
stickerView.replace(sticker);


where is from input?

**Comment by Mayurdudhat** [comment]
i want to change text on double tab textsticker .. is there any solution of it ?

**Comment by gautamlodaliya** [comment]
> TextSticker dump = (TextSticker) stickerViewx.getCurrentSticker();
> recentText= input.toString();
> final TextSticker sticker = new TextSticker(EditingActivity.this);
> sticker.setText(input+"");
> sticker.setMaxTextSize(500);
> sticker.setTextColor(dump.getTextColor());
> sticker.setTypeface(dump.getTypeface());
> sticker.setTextAlign(Layout.Alignment.ALIGN_CENTER);
> sticker.resizeText();
> stickerView.replace(sticker);

what is input here
