### ISSUE TITLE
How can I get the TextSticker 's textSize?

### ISSUE THREAD

**Issue by wangyuan0217** [wuapnjie/StickerView#144]

**Comment by dengyuhan** [comment]
```
sticker.getStaticLayout().getPaint().getTextSize()
```

**Comment by wangyuan0217** [comment]
上面的值还要乘sticker?.currentScale 吧，不知道为什么刚开始加了字这个scale为什么不是1，还有能否让StaticLayout与文字的宽度自适应啊，现在这个宽度是固定的。我想获取到文字的左上角的坐标(不是边框的左上角坐标)不知道有没有办法，

**Comment by xiandanin** [comment]
初始化时在[addStickerImmediately()](https://github.com/wuapnjie/StickerView/blob/master/sticker/src/main/java/com/xiaopo/flying/sticker/StickerView.java#L720)中自动缩放了，不一定是1

自适应要重写`resize()`方法了

**Comment by wangyuan0217** [comment]
目前的需求是 gif 上面加文字，用了这个库。我的方案是gif拆帧，然后给每个bitmap加字，所以要拿到文字的位置等信息，然后在合成gif
