### ISSUE TITLE
Saved Text Stickers are very low quality.

### ISSUE THREAD

**Issue by brije111** [wuapnjie/StickerView#15]
![1486968298309](https://cloud.githubusercontent.com/assets/11292348/22873685/a0ac0bae-f1e7-11e6-9f66-2a155415b705.jpg)

How to improve image quality while saving to memory. Text sticker look very bad in quality.

**Comment by brije111** [comment]
Solved!!!! got better image with saving in PNG format.

**Comment by wuapnjie** [comment]
Congratulations！I will add new methods to save as PNG image.Thanks for your advice.
