### ISSUE TITLE
In StickerView.getCurrentSticker.setMatrix() not works. Sticker always stay on center position

### ISSUE THREAD

**Issue by nayankukadiya** [wuapnjie/StickerView#26]
I am developing application i which we can store sticker matrix positions in internal storage and restore sticker using old matrix position.
In that i get matrix value in float array of size 9 and restore it by float array but still always sticker added in center position.
After that i tried to replace sticker with setMatrix method but still it can't change position pragmatically.
So Please help me store and retrieve sticker positions.

**Comment by wuapnjie** [comment]
Ok，Give me some time.

**Comment by nayankukadiya** [comment]
Thank you for your response. But now its work.

My mistake was that i set Metrix to on create Activity after initialization of StickerView.
So Now I added some code to add matrix and its work.

stickerView.post(new Runnable() {
            @Override
            public void run() {
                // added new sticker or set matrix here.
            }
        });
Thanks a lot again.

**Comment by chnouman** [comment]
hy @nayankukadiya  please help me Sticker.Positions are not working for me it always paste sticker in center. i want it to be bottom

**Comment by MirkoWu** [comment]
+1，Can you solve it？
