### ISSUE TITLE
How to add onClick callback to each Sticker

### ISSUE THREAD

**Issue by newCaoTao** [wuapnjie/StickerView#6]
How to add onClick callback to each Sticker?

**Comment by wuapnjie** [comment]
sorry,c currently I did not add this function. But it is easy to add a
callback in onTouchEvent.Tonight , I will add this function.Thanks for your
feedback.

**Comment by newCaoTao** [comment]
Well , thanks.
BTW, when you add , could you think about how to replace bitmap of each Sticker when performClick ?

**Comment by wuapnjie** [comment]
I will add one method to support. Did any other function which is common?

**Comment by newCaoTao** [comment]
Thanks.
No more so far...

**Comment by newCaoTao** [comment]
Oh, I remind two other function:
1. how to get the angle of rotation about each sticker.
2. how to get the with & height px of each sticker after zooming.

**Comment by wuapnjie** [comment]
I am just add OnClick func and replace func. And I add Sticker some methods to get its current info

**Comment by newCaoTao** [comment]
Thanks, it helps me a lot.
BTW, could you add one more function:
which to get the paddingTop & paddingLeft of screen of each sticker

**Comment by newCaoTao** [comment]
sorry to disturb you..
could you add the padding func tonight? I should use it till tomorrow. thanks a lot

**Comment by wuapnjie** [comment]
You can easily get the four cornors'position by `getBoundPoints()` methods.This position is the related position in View. So you can calculate some info you need.

**Comment by newCaoTao** [comment]
I get it, thanks

**Comment by newCaoTao** [comment]
can you understand Chinese? I have an issue about adding sticker view

**Comment by wuapnjie** [comment]
这，我就是说中文的

**Comment by newCaoTao** [comment]
太好了。
是这样的，我现在遇到一个问题。当一个stickerview里面加了几个sticker，每个sticker的位置不一样，然后移动任意几个sticker的位置，然后保存它们的位置。下次创建这个界面（根据上次保存的每个sticker位置创建），发现sticker的位置跟上次不一样了，根据效果，感觉如果有多个sticker，会相互影响位置

**Comment by newCaoTao** [comment]
我尝试格掉了stickerview里面的transformSticker方法，发现会好一些，但是还是会有一些不太准，跟上次保存的位置

**Comment by wuapnjie** [comment]
只要每个Sticker的Matrix的变换相同，那么它的位置，缩放，旋转等信息肯定是一样的，你要想办法保存下那个Matrix的信息

**Comment by newCaoTao** [comment]
我保存了平移的x,y坐标，旋转角度，缩放比例，然后addsticker的时候传进去进行绘制

**Comment by newCaoTao** [comment]
不好意思再请教一个addSticker的问题：
我现在的需求是要在相对于屏幕marginLeft,marginTop的位置，添加一个图片。
我在addSticker方法里这么写，但是发型移动的位置不对，请教要怎么修改：
public void addSticker(String index, Drawable stickerDrawable, float leftMargin, float topMargin, float width, float height, float rotate) {

        Sticker drawableSticker = new DrawableSticker(stickerDrawable);

        float scaleX = width / stickerDrawable.getIntrinsicWidth();
        float scaleY = height / stickerDrawable.getIntrinsicHeight();

        drawableSticker.getMatrix().reset();

        Matrix matrix = new Matrix();
        matrix.postTranslate(leftMargin,topMargin);
        matrix.postRotate(rotate);
        matrix.postScale(scaleX,scaleY, getWidth() / 2, getHeight() / 2);

        drawableSticker.getMatrix().set(matrix);

        mHandlingSticker = drawableSticker;
        mStickers.add(drawableSticker);
        stickerMap.put(index,drawableSticker);

        invalidate();
    }

**Comment by wuapnjie** [comment]
缩放中心默认，就是postScale(scaleX,scaleY)就好了

newCaoTao <notifications@github.com>于2016年11月25日周五 下午4:18写道：

**Comment by newCaoTao** [comment]
我试过了，也是不行哦。margin的位置总是不对。

**Comment by newCaoTao** [comment]
我也同步修改了transformSticker方法
private void transformSticker(Sticker sticker) {
        if (sticker == null) {
            Log.e(TAG, "transformSticker: the bitmapSticker is null or the bitmapSticker bitmap is null");
            return;
        }

        if (mSizeMatrix != null) {
            mSizeMatrix.reset();
        }

        mSizeMatrix.postTranslate(leftMargin, topMargin);

        float scaleX = width / sticker.getWidth();
        float scaleY = height / sticker.getHeight();

        //mSizeMatrix.postTranslate(leftMargin, topMargin);
        //根据宽高进行缩放到指定尺寸
        mSizeMatrix.postScale(scaleX, scaleY);

        //设置旋转角度
        mSizeMatrix.postRotate(rotate);

        sticker.getMatrix().reset();
        sticker.getMatrix().set(mSizeMatrix);

        invalidate();

    }

**Comment by wuapnjie** [comment]
是怎么样子的？我在本地测时，貌似是可以的，我单纯将postTranslate(200,200),缩放中心在图片左上角时，也就是(0,0)时，是正确的，若果缩放中心在中心处，缩放比>1,则会使移动距离缩小，反之会使移动距离减小，因为矩阵操作和操作的顺序有关，所以你要决定操作顺序。

newCaoTao <notifications@github.com>于2016年11月25日周五 下午4:54写道：

**Comment by newCaoTao** [comment]
操作顺序是指平移，缩放的顺序嘛？要怎么决定操作顺序呢？

**Comment by wuapnjie** [comment]
额，这个我说不清楚呢，不过网上有很多讲解Matrix在自定义View的作用，建议去看一下，特别有用

**Comment by luo15140128** [comment]
您好，如何将StickerView兼容photoview下进行标注？

**Comment by wuapnjie** [comment]
现在StickerView可以愉快的和PhotoView进行交互了，具体可以看demo
