### ISSUE TITLE
how to set minimum and maximum sticker size?

### ISSUE THREAD

**Issue by rahul107** [wuapnjie/StickerView#60]
i want to set minimum sticker size and maximum sticker size because when sticker get too small it losses functionality and can't show close,flip icon.

**Comment by Surabhi3** [comment]
Pls reply if this issue is solved

**Comment by rahul107** [comment]
not solve this issue

**Comment by Surabhi3** [comment]
public void zoomAndRotateSticker(@Nullable Sticker sticker, @NonNull MotionEvent event) {
    if (sticker != null) {
        float newDistance = calculateDistance(midPoint.x, midPoint.y, event.getX(), event.getY());
        float newRotation = calculateRotation(midPoint.x, midPoint.y, event.getX(), event.getY());
        moveMatrix.set(downMatrix);
        x = newDistance;

        if(x<=150f){
          moveMatrix.postScale(1f,1f);
          moveMatrix.postRotate(newRotation - oldRotation, midPoint.x, midPoint.y);
        }
      else{
          moveMatrix.postScale(newDistance/oldDistance, newDistance/oldDistance, midPoint.x, midPoint.y);
          moveMatrix.postRotate(newRotation - oldRotation, midPoint.x, midPoint.y);
          handlingSticker.setMatrix(moveMatrix);
       }


    }
  }
