### ISSUE TITLE
Constraining Sticker to image boundaries 

### ISSUE THREAD

**Issue by SimpleSmiki** [wuapnjie/StickerView#9]
Is there a way to constrain user in moving a sticker, so he couldn't be able to move it outside of the parent image view?

I am grateful for any help and advice.

Keep up the good work. :)

**Comment by wuapnjie** [comment]
Currently,the sticker can move in any position in the view.If the
StickerView'width and height equal to ImageView' width and height.The
constrain of moving is image boundaries.

**Comment by AnuragKataria** [comment]
there is one bug in the stickerView if we load sticker on button click then it is not showing on the stickerview. It is showing after touch the StickerView Please help me to get rid from this problem

**Comment by wuapnjie** [comment]
ok,i will check and fix it. It will be quick.

**Comment by wuapnjie** [comment]
I update the code.You can see it in GitHub.In my device.The replace func
works well.

**Comment by SimpleSmiki** [comment]
Cool. 

I noticed one thing in this new version - when I add new sticker on some event, it's not drawn until StickerView is clicked. I believe invalidate() is missing at the end of addSticker method. 

And about the issue from above, I would like to somehow restrict user from hiding the sticker on a image, or at least make it to be 50% visible. For example, that you can't move the center of the sticker across the image boundaries.

**Comment by wuapnjie** [comment]
Oh,sorry.It's my negligence.And I understand your demand.But in my
area.It's too late at night.So I will fix it and add an alternative method
to constrain the sticker move area.

**Comment by SimpleSmiki** [comment]
Thanks a ton! Really appreciate it.

**Comment by luo15140128** [comment]
您好，如何将StickerView兼容photoview下进行标注？

**Comment by wuapnjie** [comment]
不好意思，目前还无法和PhotoView愉快的玩耍，要研究一下，Sorry

2016-12-12 18:48 GMT+08:00 luo15140128 <notifications@github.com>:

**Comment by luo15140128** [comment]
可以研究下下喔 呵呵

**Comment by luo15140128** [comment]
刚刚看了下photoview上添加水印标注，有如下问题： （1）图片水印移动的时候部分超出照片范围外，（2）放大缩小图片的时候标注未跟着移动。  最大的难点是如何标注之后图片放大缩小，标注也跟着移动变化呢

**Comment by wuapnjie** [comment]
恩，我再研究研
